eureka:
  client:
    register-with-eureka: false
server:
  port: 8223
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/bet/**


management:
  tracing:
    sampling:
      probability: 1.0
